# Generated by Django 3.2 on 2021-10-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=550, verbose_name='Javob')),
                ('image', models.ImageField(blank=True, upload_to='answers_img/', verbose_name='rasmi')),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2150, verbose_name='Savol')),
                ('answers', models.ManyToManyField(related_name='quizzs', to='main.Answers')),
                ('true_answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizz', to='main.answers')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=150, verbose_name='Familiya')),
                ('true_a', models.ManyToManyField(related_name='user_true', to='main.Quizzes')),
            ],
        ),
    ]
