# Generated by Django 3.2 on 2021-10-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_false_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='true_answer',
        ),
        migrations.AddField(
            model_name='answers',
            name='true_or_false',
            field=models.BooleanField(default=True, verbose_name='togrimi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tel_num',
            field=models.PositiveIntegerField(default=False, verbose_name='telfon raqami'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='times',
            field=models.CharField(blank=True, choices=[('ERTALABKI', 'ertalabki'), ('KECHKI', 'kechki')], max_length=150),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='answers',
            field=models.ManyToManyField(related_name='ans_quizz', to='main.Answers'),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='ways',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='way_quizz', to='main.ways'),
            preserve_default=False,
        ),
    ]
