# Generated by Django 3.2.4 on 2021-10-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211018_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='ways',
            name='icon',
            field=models.CharField(default=0, max_length=50, verbose_name='Icon fontaosem'),
            preserve_default=False,
        ),
    ]
